name: codemelted_developer
description: ""
version: 0.1.0
homepage: https://developer.codemelted.com

platforms:
  web:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  pointer_interceptor: any
  web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  assets:
  - npu/codemelted.wasm
  - pwa/codemelted.js