name: codemelted_developer
description: "The codemelted.dart module brings the power of Flutter to the web with its rich widget toolset leveraging a professional polish and feel without needing HTML or CSS."
version: 0.0.0
homepage: https://codemelted.com/developer

platforms:
  web:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  pointer_interceptor: any
  web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  assets:
  - assets/cpp/docs/codemelted.wasm
  - assets/cpp/docs/codemelted.js