[book]
title = "CodeMelted DEV | pwsh Module"
authors = ["Mark Shaffer"]
description = ""
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[output.html]
default-theme = "navy"
site-url = "https://codemelted.com/developer/codemelted_dev/"
git-repository-url = "https://github.com/codemelted/codemelted_developer"
