[book]
title = "The CodeMelted DEV Rosetta Stone"
authors = ["Mark Shaffer"]
description = "An implementation of 14 domain specific use cases in different programming languages forming a translation between those given languages and providing a swiss-army knife module for the identified language / SDK."
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[output.html]
default-theme = "navy"
site-url = "https://developer.codemelted.com/projects/rosetta-stone"
git-repository-url = "https://github.com/codemelted/codemelted_developer"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
