---
title: codemelted_hw Module
---
classDiagram
  direction TB
  namespace codemelted {
    class codemelted_hw {
      +available_bluetooth_devices() Vec
      +available_serial_ports() Vec
      +kernel_version() String
      +monitor() CComponentMonitor
      +open_bluetooth_device(CBluetoothInfo) CBluetoothDevice
      +open_serial_port(SerialPortInfo) CSerialPort
      +os_name() String
      +os_version() String
      +user() String
    }
    class CBluetoothDevice {

    }
    class CBluetoothInfo {
      +id() String
      +address() String
    }
    class CComponentMonitor {
      -new() CComponentMonitor
      +refresh()
      +len() usize
      +label(index) String
      +temp_current_c(index) f32
      +temp_max_c(index) f32
      +temp_critical_c(index) f32
    }
    class CSerialPortData {
      +ErrorDetected
      +BaudRate
      +DataBits
      +FlowControl
      +Parity
      +StopBits
      +Timeout
      +ClearBuffer
      +CarrierDetect
      +ClearToSend
      +DataSetReady
      +RequestToSend
      +RindIndicator
      +ReadData
      +WriteData
      +as_bool(self) Option
      +as_bytes(self) Option
      +as_data_bis(self) Option
      +as_flow_control(self) Option
      +as_parity(self) Option
      +as_timeout(self) Option
      +get_message_request(self) Option
    }
    class CSerialPort {
      -port SerialPort
      -error Option
      -new() CSerialPort
      -port_ref() SerialPort
    }
    class CCsvFormat {
      +csv_header() String
      +as_csv() String
    }
    class CProtocolHandler {
      +error() Option
      +get_message(request) T
      +id() String
      +is_running() bool
      +post_message(data)
      +terminate()
    }
  }
  namespace btleplug {
    class Manager
    class Peripheral
  }
  namespace serialport {
    class ClearBuffer
    class DataBits
    class FlowControl
    class Parity
    class SerialPort
    class SerialPortInfo
    class StopBits
  }
  namespace sysinfo {
    class Components
    class System
  }
  codemelted_hw --> CBluetoothInfo: creates
  codemelted_hw --> CBluetoothDevice: creates
  codemelted_hw --> CComponentMonitor: creates
  codemelted_hw --> CSerialPort: creates
  codemelted_hw --> Manager: uses
  CBluetoothInfo --> Peripheral: uses
  CSerialPort --> CSerialPortData: uses / crates
  CSerialPortData --> ClearBuffer: uses
  CSerialPortData --> DataBits: uses
  CSerialPortData --> FlowControl: uses
  CSerialPortData --> StopBits: uses
  CSerialPort --> CProtocolHandler: implements
  CSerialPort --> SerialPort: uses
  codemelted_hw --> SerialPortInfo: uses
  CComponentMonitor --> CCsvFormat: implements
  CComponentMonitor --> Components: uses
  CComponentMonitor --> System: uses
