---
title: Logger Use Case Object Hierarchy
---
classDiagram
  direction LR
  namespace codemelted {
    class CLogLevel {
      +Debug
      +Info
      +Warning
      +Error
      +Off
      +as_string(self) String
      +as_int(self) u8
    }
    class CLogRecord {
      +get_time_stamp(): DateTime
      +get_log_level(): CLogLevel
      +get_data(): String
      +as_string(): String
    }
    class CLogEventHandler {
      +fn(CLogRecord)
    }
    class logger_get_log_level
    class logger_set_log_level
    class logger_get_log_handler
    class logger_set_log_handler
    class logger_log
  }
  namespace chrono {
    class DateTime
  }
  CLogRecord --> CLogLevel: uses
  CLogRecord --> DateTime: uses
  logger_get_log_level --> CLogLevel: uses
  logger_set_log_level --> CLogLevel: uses
  logger_get_log_handler --> CLogEventHandler: uses
  logger_set_log_handler --> CLogEventHandler: uses
  logger_log --> CLogRecord: creates
  logger_log --> CLogLevel: uses
  logger_log --> CLogEventHandler: calls